obsolete, hash, ...

diff --git a/srvbak b/srvbak
--- a/srvbak
+++ b/srvbak
@@ -11,13 +11,33 @@
 #
 # --                                                            ; }}}1
 
-source "$1" || exit 1
+set -e
+source "$1"
 
-date="$( date +'%FT%T' )"
+export LC_COLLATE=C
+date="$( date +'%FT%T' )"   # no spaces!
 
+# Usage: run <cmd> <arg(s)>
 function run () { echo "==> $@"; "$@"; echo; }
+
+# Usage: run_multi <cmd1-with-args> <cmd2-with-args> ...
 function run_multi () { local x; for x in "$@"; do run $x; done; }
 
+# Usage: canonpath <path>
+# No physical check on the filesystem, but a logical cleanup of a
+# path.
+function canonpath ()
+{ perl -MFile::Spec -e 'print File::Spec->canonpath($ARGV[0])' "$1"; }
+
+# Usage: hashpath <path>
+# SHA1 hash of canonical path.
+function hashpath ()
+{ printf '%s' "$( canonpath "$1" )" | sha1sum; }
+
+# --
+
+# Usage: process_mongo_passfile
+# Uses $mongo_passfile; sets $mongo_auth__${db}__{user,pass}.
 function process_mongo_passfile ()
 {                                                               # {{{1
   local oldifs="$IFS" db user pass
@@ -30,20 +50,69 @@ function process_mongo_passfile ()
   IFS="$oldifs"
 }                                                               # }}}1
 
+# Usage: ls_backups <dir>
+function ls_backups ()
+{ local dir="$1"; ls "$dir" | grep -E '^[0-9]{4}-'; }
+
+# Usage: last_backup <dir>
+function last_backup ()
+{ local dir="$1"; ls_backups | tail -n 1; }
+
+# Usage: obsolete_backups <dir>
+function obsolete_backups ()
+{ local dir="$1"; ls_backups | head -n -"$keep_last"; }
+
+# Usage: cp_last_backup <dir> <path>
+# Copies last backup in <dir> (if one exists) to <path> using hard
+# links.
+# NB: call before new backup (or dir creation)!
+function cp_last_backup ()
+{                                                               # {{{1
+  local dir="$1" path="$2"
+  local last="$( last_backup "$dir" )"
+
+  if [ -n "$last" -a -e "$last" ]; then
+    run cp -alT "$last" "$path"
+  fi
+}                                                               # }}}1
+
+# Usage: rm_obsolete_backups <dir>
+# NB: call after new backup!
+function rm_obsolete_backups ()
+{                                                               # {{{1
+  local dir="$1" x
+
+  for x in $( obsolete_backups "$dir" ); do
+    run echo rm -r "$x"                                         # TODO
+  done
+}                                                               # }}}1
+
+# --
+
+# Usage: pg_backup <dbname>
+# PostgreSQL dump to $base_dir/postgresql/$dbname/$date.sql.
+# Removes obsolete backups.
+# Uses $PG*.
 function pg_backup ()
 {                                                               # {{{1
   local dbname="$1"
-  local dir="$base_dir"/postgresql/"$dbname"
+  local dir="$base_dir/postgresql/$dbname"
   local dump="$dir/$date".sql
 
   mkdir -p "$dir"
   run pg_dump "$dbname" -f "$dump" -w
+
+  rm_obsolete_backups "$dir"
 }                                                               # }}}1
 
+# Usage: mongo_backup <dbname>
+# MongoDB dump to $base_dir/mongodb/$dbname/$date.
+# Removes obsolete backups.
+# Uses $mongo_{host,auth__${dbname}__{user,pass}}.
 function mongo_backup ()
 {                                                               # {{{1
   local dbname="$1" user pass
-  local dir="$base_dir"/mongodb/"$dbname"
+  local dir="$base_dir/mongodb/$dbname"
   local dump="$dir/$date"
 
   [[ "$dbname" =~ ^[A-Za-z0-9]+$ ]] || exit 1
@@ -53,15 +122,31 @@ function mongo_backup ()
   mkdir -p "$dir"
   echo "$pass" | run mongodump -h "$mongo_host" -d "$dbname" \
     -u "$user" -p '' -o "$dump"
+
+  rm_obsolete_backups "$dir"
 }                                                               # }}}1
 
+# Usage: data_backup <dir>
+# rsync directory to $base_dir/data/$hash_of_dir, symlinked from
+# $base_dir/data/path/$dir.
+# Removes obsolete backups.
 function data_backup ()
 {                                                               # {{{1
-  local dir="$1"
-  local to="$base_dir"/data/"$dir"/"$date"
+  local data="$1"
+  local hash="$( hashpath "$data" )"
+  local ddir="$base_dir"/data
+  local dir="$ddir/$hash"
+  local to="$dir/$date"
 
-  mkdir -p "$to"
-  run rsync -a --delete "$dir"/ "$to"/
+  mkdir -p "$dir"
+  cp_last_backup "$dir" "$to"
+
+  run rsync -a --delete "$data"/ "$to"/
+
+  mkdir -p "$ddir/path/$( dirname "$data" )"
+  run ln -s "$dir" "$ddir/data/path/$data"
+
+  rm_obsolete_backups "$dir"
 }                                                               # }}}1
 
 # --
